### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by slava-osipov-qs** [eigenmethod/mam#11]
I'm unable to start dev server using suggested instructions on Windows 10
Here is the log:
[start.log](https://github.com/eigenmethod/mam/files/3388620/start.log)
After insterrupting script I can see that file c:\Temp\1\mam\mol\build\-\index.html has content:

> null

UPD:

> node --version
> v10.3.0
> npm --version
> 6.1.0

**Comment by nin-jin** [comment]
> After insterrupting script I can see that file c:\Temp\1\mam\mol\build-\index.html has content:

Это сейчас нормально. Надо будет добавить условие, чтобы файл не создавался, если контента для него нет.

**Comment by nin-jin** [comment]
У меня не получается воспроизвести эту проблему.

**Comment by nin-jin** [comment]
Возможно нужна более свежая версия ноды?

**Comment by slava-osipov-qs** [comment]
Я не знаю в чём причина проблемы. Так что вполне возможно на вашей версии ноды и не воспроизводится. Насколько мне известно fs.lstat в ноде в какой-то момент менялся.

**Comment by slava-osipov-qs** [comment]
Most recent `node` (12.6.0) solved the problem
